spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.79.130:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&useSSL=false
    username: root
    password: 123456
  transaction:
      rollback-on-commit-failure: true

  redis:
    host: 192.168.49.130
    jedis:
      pool:
        max-idle: 8
        max-active: 10
        min-idle: 2
        max-wait: 100ms

  mail:
    host: smtp.exmail.qq.com
    username: fliu@dunoinfo.com
    password: oR4XzPJnKyffpAGR
    default-encoding: UTF-8
    port: 465

    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
      debug: true