spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.79.130:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&useSSL=false
    username: root
    password: 123456
  transaction:
      rollback-on-commit-failure: true
